[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Lox插件

## 1\.Language and File Type

### FileType

#### 定义后缀

#### 定义Language

#### 指定文件类型图标

### FileTypeFactor

## Gramar and Parser

### TokenType类

#### 继承IElementType

### 创建一个XXX\.bnf指定语言的语法

#### bnf文件右键能选择<br/>Generate Parser Code<br/>能生成Parser代码

#### 右键再标记为Generated Sources Root

## Tutorial
> leftSide=`true`

- LINK
<pre>https://intellij-sdk-docs-cn.github.io/intellij/sdk/docs/tutorials/custom_language_support_tutorial.html</pre>

## 3\.Lexer and Parser Definition
> leftSide=`true`


### Define a Lexer

#### 创建一个XXX\.flex的文件，指明各种解析类

## SyntaxHighlighterAnd Color Setting Pagde
> leftSide=`true`


### 创建一个继承SyntaxHighlighterBase 的就可以有高亮效果了

### 定义一个 ColorSettingsPage 就可以设置界面设置支持的高亮方案 
> leftSide=`true`


## PSI Helpers and Utilities

### 定义PSI Impl类 并且在bnf里面指明<br/>psiImplUtilClass 是哪个类

### 右键bnf文件重新生成Parser代码
